# fly.toml app configuration file generated for portfolio-stage on 2024-07-27T16:43:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-stage'
primary_region = 'ams'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
