# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3615d309d910bbdefb0297feee282560"
name = "portfolio-dev"
handle = "portfolio-dev"
application_url = "https://phoenix-rack-retail-dominican.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "portfolio-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes"

[auth]
redirect_urls = [
  "https://phoenix-rack-retail-dominican.trycloudflare.com/auth/callback",
  "https://phoenix-rack-retail-dominican.trycloudflare.com/auth/shopify/callback",
  "https://phoenix-rack-retail-dominican.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
